
	#define TOKEN_RESERVADA_C 1
	#define TOKEN_COMENTARIO_MULTILINEA_C 2
	#define TOKEN_COMENTARIO_LINEA_C 3
	#define TOKEN_VARIABLE_C 4
	#define TOKEN_CONSTANTE_NUMERICA_C 5
	#define TOKEN_OPERADOR_ARITMETICO_C 6
	#define TOKEN_OPERADOR_LOGICO_C 7
	#define TOKEN_SIMBOLO_ESPECIAL_C 8
